name: exercise_3
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - protobuf==3.20.*
  - pip=20.3.3
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - numpy==1.23.*
  - pip:
      - wandb==0.10.21
